### ISSUE TITLE
No locale when installed with pip

### ISSUE THREAD

**Issue by adrien-delhorme** [stefanfoulis/django-phonenumber-field#116]
After a `pip install django-phonenumber-field`
the installed package does not contain a `locale/` directory.

I think `recursive-include phonenumber_field/locale *` is missing in `MANIFEST.in`.

**Comment by amateja** [comment]
Hi @adrien-delhorme.

That's true. I think it's because package is build as an egg. This project is OS independent so we might produce a wheel instead and there is no such issue.

Locales are included during build phase thanks to https://github.com/stefanfoulis/django-phonenumber-field/blob/develop/setup.py#L22-L26 but are not included in source distribution creation and I have a feeling that it shouldn't be made that way (I mean with package_data).
