### ISSUE TITLE
Incorrect country displayed in PhoneNumberPrefixWidget select dropdown

### ISSUE THREAD

**Issue by marcua** [stefanfoulis/django-phonenumber-field#125]
Hello!  Thanks for making a great library!  We found a small bug-o.  If I select a country with a country code that overlaps with another country, e.g.:

![image](https://cloud.githubusercontent.com/assets/57725/15076935/1273de08-137a-11e6-9ee9-5fc73db4edce.png)

Then on save, the country code widget will display the country that has the same country code but appears first by sort order, e.g.,:

![image](https://cloud.githubusercontent.com/assets/57725/15076956/2bea7356-137a-11e6-8e92-bfa4e6c08d67.png)

If the values of the `PhoneNumberPrefixWidget`'s `select` element were the countries instead of the country codes, this issue would go away.  Is there a workaround?  If not, we can submit a PR to fix this.  Thanks!

**Comment by amateja** [comment]
Hi @marcua 

Thank you for reporting. Your problem is well known I'm afraid. Would you like to have a look on #82 because your problem is a duplicate? Sadly there is no easy fix... especially PhoneNumberField supports 5 Django versions. At some point we will have to face sweeping changes and on that stage we could include a patch for it.

**Comment by marcua** [comment]
Thanks for the fast reply!  I'll close for now since it's a duplicate.
