### ISSUE TITLE
How to handle varying formats in conjunction with faker

### ISSUE THREAD

**Issue by step21** [stefanfoulis/django-phonenumber-field#319]
Hi,

I am trying to use phonenumber-field in conjunction with python faker to generate  test data.
Unfortunately, it seems that sometimes ti generates numbers that seem valid, but are actually not according to phonenumber-field. Could this be because locale is not set correctly or because it sees some numbers as wrong that might not be. (such as 0049 vs +49 and +49 (0)711 4234932
(where the 0 is in brackets to indicate it is only needed in some cases.) I think that was one example... kind of hard to generate many good examples because it always errors out and they are random.

**Comment by benefacto** [comment]
We're also running into this. It's disappointing that we have to hard code phone numbers in our test suite rather than have some means of generating valid fake phone numbers that phonenumber-field can accept. I wish it did not fail validation without expressing exactly what is failing, since it is being passed what are valid phone numbers.

**Comment by francoisfreitag** [comment]
> Unfortunately, it seems that sometimes ti generates numbers that seem valid, but are actually not according to phonenumber-field.

Phone number field delegates to [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers), which itself delegates to [libphonenumbers](https://github.com/google/libphonenumber). That library has precise knowledge of phone numbers, much beyond “looking valid”. It knows what range of phone numbers are assigned, to which carrier, specific per-carrier rules and more.
For example, an invalid North American regional prefix won’t pass validation, even if the number is properly formatted.
Can also look at the example from https://github.com/daviddrysdale/python-phonenumbers#example-usage.

> since it is being passed what are valid phone numbers.

A valid phone number is accepted by django-phonenumber-field. The fact that a number looks valid does not mean it actually is.

---
> Could this be because locale is not set correctly or because it sees some numbers as wrong that might not be. (such as 0049 vs +49 and +49 (0)711 4234932

If you use a faker locale to generate the phone number, then it looks like faker will generate numbers in the international and in the national format https://github.com/joke2k/faker/blob/0ebe46fc9b9793fe315cf0fce430258ce74df6f8/faker/providers/phone_number/fr_FR/__init__.py.

That means you need to configure the phonenumber field to match what Faker provides (i.e. use the faker locale as the field region). Otherwise, the library does not have enough contextual data to interpret the phone number and cannot guess what region it comes from.

---

I don’t think the issue with the django-phonenumber-field project. Faker can probably be improved to generate more realistic phone numbers. If a phone number that is valid for `libphonenumber` is rejected by django-phonenumber-field, please reopen the issue with the number that is handled incorrectly.
