### ISSUE TITLE
Broken localization of form error

### ISSUE THREAD

**Issue by washeck** [stefanfoulis/django-phonenumber-field#358]
The translation catalogs have `fuzzy` mark on ""Enter a valid phone number (e.g. {example_number})." message causing this message not being translated.

I verified it on Czech and Dutch translations so I guess it affects all languages:

https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/locale/cs/LC_MESSAGES/django.po#L29
https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/locale/nl/LC_MESSAGES/django.po#L28

**Comment by MikePooh** [comment]
Same thing observing on Russian language as well

**Comment by maysu1914** [comment]
Man, I have this problem too, and I thought I was doing something wrong when adding localization to the project. I changed the error message with another message and the translation worked, so that fuzzy string was the problem from the beginning.

https://stackoverflow.com/questions/65737416/language-selection-of-third-party-packages-django

**Comment by max-arnold** [comment]
I fixed the Russian translation here: https://github.com/stefanfoulis/django-phonenumber-field/pull/444
