### ISSUE TITLE
validate_international_phonenumber does not validate correctly at some cases

### ISSUE THREAD

**Issue by MrArabboy** [stefanfoulis/django-phonenumber-field#595]
While validating Uzbek phone numbers , if I add one or two letters after or within phone number **validate_international_phonenumber**  consider as a valid phone number why ?  
![image](https://github.com/stefanfoulis/django-phonenumber-field/assets/50806541/6f0b0aeb-cae6-4720-afd7-d5366bcc213d)

**Comment by francoisfreitag** [comment]
Because it can parse a valid from number from the string. The library uses `parse` for more user-friendly interactions. Many countries have different conventions for annotating phone numbers (grouping, separators, ...). As an example :
France : `"06 12 34 56 78"`
Canada : `"604 401-1234"`, or even `"604 GOT JUNK"`

When users from a region use their familiar representation of a phone number, they expect the system to recognize their numbers, which involves parsing.
