### ISSUE TITLE
python-phonenumbers should be a requirement

### ISSUE THREAD

**Issue by arveitch** [stefanfoulis/django-phonenumber-field#606]
I think you just need a setup.py with python-phonenumbers and the required version specified.

That way it is automatically installed for anyone who installs this package from pip

Thanks for your work on a great product!

**Comment by francoisfreitag** [comment]
Hi,

The `phonenumbers` package actually provides two alternatives, https://django-phonenumber-field.readthedocs.io/en/latest/#choosing-a-phonenumbers-provider, see https://github.com/daviddrysdale/python-phonenumbers?tab=readme-ov-file#memory-usage. That’s why `phonenumbers` is not a required package, because `phonenumberslite` may be sufficient for most users, and is considerably smaller.
