### ISSUE TITLE
Widget initial by label, not value (country code US does not initialize as United States)

### ISSUE THREAD

**Issue by nwaxiomatic** [stefanfoulis/django-phonenumber-field#82]
I am trying to set the initial value of the Prefix select, the issue is that when using initial='US' the select defaults to "American Samoa" because it is the first item in the list with the value of "+1", rather than "United States".

Is there a way to set the initial value based on the label rather than the value because of the duplicate country codes?

**Comment by evansnj** [comment]
+1, I'm running into the same issue and haven't found any way around it yet.

**Comment by cloudcoderuwu** [comment]
Basically we need to rewrite the widget so that the value stores the country code and only decompresses to the actual value. Currently there are multiple items in the drop down with the same value. The widget then just takes that value as the prefix and appends to the rest of the number.

**Comment by cloudcoderuwu** [comment]
After some investigating I found these issues:

The python package this depends on, phonenumbers, doesn't store the region code (ie 'US'), it stores the country code (ie '+1'), and the function it has built in to decipher the region code works kind of like this:
 
```
COUNTRY_CODES = {1:{'AA', 'BB',..., 'US',...},...}
def region(country):
    regions = COUNTRY_CODES.get(country, None)
    return regions[0]
```

so I'm not sure if the solution is to build on top of this, by adding the region code as a stored part of the phonenumber in the django app, or modifying the python package at the root to actually keep track of it and get the region from storage.

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.

**Comment by nwaxiomatic** [comment]
v 0.7.2 has not fixed this issue

**Comment by amateja** [comment]
How about v 1.0.0.0? :smile:

**Comment by nwaxiomatic** [comment]
I'm not seeing in the repo where this would have been fixed, the model still only stores the pythonic phonenumber, which does not store the country beyond its code, which is not a 1-1 function.

**Comment by nwaxiomatic** [comment]
Still does not work with 1.0

**Comment by amateja** [comment]
I had a second glance on your problem and I'm not really sure if it should be fixed in this project. I think phone number meant to be stored in DB in international format as CharField. I think @stefanfoulis should say a word or it should be changed in https://github.com/daviddrysdale/python-phonenumbers.

**Comment by nwaxiomatic** [comment]
Yeah, it's a tricky problem and I spent a day or so (to no avail) trying to find an easy way around it.
Either there needs to be another field on the model  through python-phonenumbers, or directly added on top in this repo. 
Either way, that change will have to be mirrored in the storage and callback all throughout the repo.

**Comment by tisdall** [comment]
I was about to report this issue but looked through closed issues first and found this and #125.  Could you re-open either this issue or #125 as they're both current problems with how the form widget works?

**Comment by lwm** [comment]
Since #125, #82 and #133 are all about this issues, it remains unresolved and is hard to track, would it be acceptable to add a 'known issues' to the README? Would have saved people time and it doesn't seem to be getting fixed anytime soon? Thanks for the library!

**Comment by Amicorp-Git** [comment]
Hi,
Iam facing the same issue of USA is replaced with American Samoa. Any fix is available?

**Comment by KunjPrasad** [comment]
Same here. I believe this is because of [this line](https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/widgets.py#L42) in `PhonePrefixSelect`. That would create an `<option>` with `value="+1"` but for multiple countries. I believe the core issue is because a E164 formatted number does not uniquely identify the country because certain phone country codes map to multiple countries. 

One quick fix could be to just display the country code, i.e. replace the entire `for country_code in values:` loop with `choices.append((prefix, prefix))`. You'll get a dropdown with values like `------` (empty string), `+1`, `+20`,`+211`, etc. ..just country codes, no country name.

I feel if it is really needed to store country values, a better solution might be to persist data in format that saves country code, like saving it as `US1234567890` instead of `+11234567890`. However, this might not be a trivial change.
